/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * AccessHistory
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class AccessHistory {

  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("anonymous")
  private Boolean anonymous = false;

  @SerializedName("protocol")
  private String protocol = null;

  @SerializedName("firstAccessTimestamp")
  private Long firstAccessTimestamp = null;
  public AccessHistory accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

  

  /**
  * The id of the account
  * @return accountId
  **/
  public String getAccountId() {
    return accountId;
  }
  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }
  public AccessHistory userName(String userName) {
    this.userName = userName;
    return this;
  }

  

  /**
  * The user name
  * @return userName
  **/
  public String getUserName() {
    return userName;
  }
  public void setUserName(String userName) {
    this.userName = userName;
  }
  public AccessHistory email(String email) {
    this.email = email;
    return this;
  }

  

  /**
  * The email address
  * @return email
  **/
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }
  public AccessHistory address(String address) {
    this.address = address;
    return this;
  }

  

  /**
  * The recipient address (the internet address user is connecting from). This property is set when the delivery method is &#x60;Anonymous&#x60;
  * @return address
  **/
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }
  public AccessHistory anonymous(Boolean anonymous) {
    this.anonymous = anonymous;
    return this;
  }

  

  /**
  * Define whether this recipient is anonymous (true if account is anonymous, false otherwise)
  * @return anonymous
  **/
  public Boolean isAnonymous() {
    return anonymous;
  }
  public void setAnonymous(Boolean anonymous) {
    this.anonymous = anonymous;
  }
  public AccessHistory protocol(String protocol) {
    this.protocol = protocol;
    return this;
  }

  

  /**
  * The protocol. Value of \&quot;http\&quot; is  hard coded.
  * @return protocol
  **/
  public String getProtocol() {
    return protocol;
  }
  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }
  public AccessHistory firstAccessTimestamp(Long firstAccessTimestamp) {
    this.firstAccessTimestamp = firstAccessTimestamp;
    return this;
  }

  

  /**
  * The time stamp when package was access for first time by this recipient.
  * @return firstAccessTimestamp
  **/
  public Long getFirstAccessTimestamp() {
    return firstAccessTimestamp;
  }
  public void setFirstAccessTimestamp(Long firstAccessTimestamp) {
    this.firstAccessTimestamp = firstAccessTimestamp;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessHistory accessHistory = (AccessHistory) o;
    return Objects.equals(this.accountId, accessHistory.accountId) &&
        Objects.equals(this.userName, accessHistory.userName) &&
        Objects.equals(this.email, accessHistory.email) &&
        Objects.equals(this.address, accessHistory.address) &&
        Objects.equals(this.anonymous, accessHistory.anonymous) &&
        Objects.equals(this.protocol, accessHistory.protocol) &&
        Objects.equals(this.firstAccessTimestamp, accessHistory.firstAccessTimestamp);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(accountId, userName, email, address, anonymous, protocol, firstAccessTimestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessHistory {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    anonymous: ").append(toIndentedString(anonymous)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    firstAccessTimestamp: ").append(toIndentedString(firstAccessTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
