/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;

import org.mule.runtime.extension.api.annotation.param.Optional;
import org.mule.runtime.extension.api.annotation.param.Parameter;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * AddressBookSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class AddressBookSettings {

  @Parameter
  @SerializedName("addressBookEnabled")
  private Boolean addressBookEnabled;

  @Parameter
  @SerializedName("addressBookCollaborationAllowed")
  private Boolean addressBookCollaborationAllowed;
  

  @Parameter
  @SerializedName("addressBookMinSearchLength")
  private Integer addressBookMinSearchLength = null;

  @Parameter
  @SerializedName("addressBookMaxDisplayEntries")
  private Integer addressBookMaxDisplayEntries = null;

  @Parameter
  @SerializedName("addressBookMaxDisplayPages")
  private Integer addressBookMaxDisplayPages = null;
  public AddressBookSettings addressBookEnabled(Boolean addressBookEnabled) {
    this.addressBookEnabled = addressBookEnabled;
    return this;
  }

  

  /**
  * Shows whether the Address Book functionality is enabled or not.
  * @return addressBookEnabled
  **/
  //(required = true, description = "Shows whether the Address Book functionality is enabled or not.")
  public Boolean isAddressBookEnabled() {
    return addressBookEnabled;
  }
  public void setAddressBookEnabled(Boolean addressBookEnabled) {
    this.addressBookEnabled = addressBookEnabled;
  }
  public AddressBookSettings addressBookCollaborationAllowed(Boolean addressBookCollaborationAllowed) {
    this.addressBookCollaborationAllowed = addressBookCollaborationAllowed;
    return this;
  }

  

  /**
  * Shows whether collaboration outside of the address book is allowed for the current user.
  * @return addressBookCollaborationAllowed
  **/
  //(required = true, description = "Shows whether collaboration outside of the address book is allowed for the current user.")
  public Boolean isAddressBookCollaborationAllowed() {
    return addressBookCollaborationAllowed;
  }
  public void setAddressBookCollaborationAllowed(Boolean addressBookCollaborationAllowed) {
    this.addressBookCollaborationAllowed = addressBookCollaborationAllowed;
  }
  public AddressBookSettings addressBookMinSearchLength(Integer addressBookMinSearchLength) {
    this.addressBookMinSearchLength = addressBookMinSearchLength;
    return this;
  }

  

  /**
  * Specifies the minimum search string length when performing wildcard search for address book entries.
  * @return addressBookMinSearchLength
  **/
  //(required = true, description = "Specifies the minimum search string length when performing wildcard search for address book entries.")
  public Integer getAddressBookMinSearchLength() {
    return addressBookMinSearchLength;
  }
  public void setAddressBookMinSearchLength(Integer addressBookMinSearchLength) {
    this.addressBookMinSearchLength = addressBookMinSearchLength;
  }
  public AddressBookSettings addressBookMaxDisplayEntries(Integer addressBookMaxDisplayEntries) {
    this.addressBookMaxDisplayEntries = addressBookMaxDisplayEntries;
    return this;
  }

  

  /**
  * Specifies the maximum limit of Address Book entries displayed in a single page.
  * @return addressBookMaxDisplayEntries
  **/
  //(required = true, description = "Specifies the maximum limit of Address Book entries displayed in a single page.")
  public Integer getAddressBookMaxDisplayEntries() {
    return addressBookMaxDisplayEntries;
  }
  public void setAddressBookMaxDisplayEntries(Integer addressBookMaxDisplayEntries) {
    this.addressBookMaxDisplayEntries = addressBookMaxDisplayEntries;
  }
  public AddressBookSettings addressBookMaxDisplayPages(Integer addressBookMaxDisplayPages) {
    this.addressBookMaxDisplayPages = addressBookMaxDisplayPages;
    return this;
  }

  

  /**
  * Specifies the maximum limit of Address Book pages in a single request.
  * @return addressBookMaxDisplayPages
  **/
  //(required = true, description = "Specifies the maximum limit of Address Book pages in a single request.")
  public Integer getAddressBookMaxDisplayPages() {
    return addressBookMaxDisplayPages;
  }
  public void setAddressBookMaxDisplayPages(Integer addressBookMaxDisplayPages) {
    this.addressBookMaxDisplayPages = addressBookMaxDisplayPages;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressBookSettings addressBookSettings = (AddressBookSettings) o;
    return Objects.equals(this.addressBookEnabled, addressBookSettings.addressBookEnabled) &&
        Objects.equals(this.addressBookCollaborationAllowed, addressBookSettings.addressBookCollaborationAllowed) &&
        Objects.equals(this.addressBookMinSearchLength, addressBookSettings.addressBookMinSearchLength) &&
        Objects.equals(this.addressBookMaxDisplayEntries, addressBookSettings.addressBookMaxDisplayEntries) &&
        Objects.equals(this.addressBookMaxDisplayPages, addressBookSettings.addressBookMaxDisplayPages);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(addressBookEnabled, addressBookCollaborationAllowed, addressBookMinSearchLength, addressBookMaxDisplayEntries, addressBookMaxDisplayPages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressBookSettings {\n");
    
    sb.append("    addressBookEnabled: ").append(toIndentedString(addressBookEnabled)).append("\n");
    sb.append("    addressBookCollaborationAllowed: ").append(toIndentedString(addressBookCollaborationAllowed)).append("\n");
    sb.append("    addressBookMinSearchLength: ").append(toIndentedString(addressBookMinSearchLength)).append("\n");
    sb.append("    addressBookMaxDisplayEntries: ").append(toIndentedString(addressBookMaxDisplayEntries)).append("\n");
    sb.append("    addressBookMaxDisplayPages: ").append(toIndentedString(addressBookMaxDisplayPages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
