/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

/**
 * Specifies the md5 checksum and the file size result of the operation.
 */
//(description = "Specifies the md5 checksum and the file size result of the operation.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class AsyncOperationResult {

  @SerializedName("fileSize")
  private String fileSize = null;

  @SerializedName("md5Checksum")
  private String md5Checksum = null;
  public AsyncOperationResult fileSize(String fileSize) {
    this.fileSize = fileSize;
    return this;
  }

  

  /**
  * Get fileSize
  * @return fileSize
  **/
  //(description = "")
  public String getFileSize() {
    return fileSize;
  }
  public void setFileSize(String fileSize) {
    this.fileSize = fileSize;
  }
  public AsyncOperationResult md5Checksum(String md5Checksum) {
    this.md5Checksum = md5Checksum;
    return this;
  }

  

  /**
  * Get md5Checksum
  * @return md5Checksum
  **/
  //(description = "")
  public String getMd5Checksum() {
    return md5Checksum;
  }
  public void setMd5Checksum(String md5Checksum) {
    this.md5Checksum = md5Checksum;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AsyncOperationResult asyncOperationResult = (AsyncOperationResult) o;
    return Objects.equals(this.fileSize, asyncOperationResult.fileSize) &&
        Objects.equals(this.md5Checksum, asyncOperationResult.md5Checksum);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(fileSize, md5Checksum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AsyncOperationResult {\n");
    
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    md5Checksum: ").append(toIndentedString(md5Checksum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
