/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;

import org.mule.runtime.extension.api.annotation.param.Parameter;
import org.mule.runtime.extension.api.annotation.param.Optional;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
//.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * ForgottenPassword
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class ForgottenPassword {

  @Parameter
  @SerializedName("token")
  private String token = null;
  
  @Parameter
  @Optional
  @SerializedName("secretAnswer")
  private String secretAnswer = null;

  @Parameter
  @Optional
  @SerializedName("username")
  private String username = null;

  @Parameter
  @SerializedName("newPassword")
  private String newPassword = null;
  public ForgottenPassword token(String token) {
    this.token = token;
    return this;
  }

  

  /**
  * Security token.
  * @return token
  **/
  //(required = true, description = "Security token.")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }
  public ForgottenPassword secretAnswer(String secretAnswer) {
    this.secretAnswer = secretAnswer;
    return this;
  }

  

  /**
  * Answer to the user&#x27;s secret question.
  * @return secretAnswer
  **/
  //(description = "Answer to the user's secret question.")
  public String getSecretAnswer() {
    return secretAnswer;
  }
  public void setSecretAnswer(String secretAnswer) {
    this.secretAnswer = secretAnswer;
  }
  public ForgottenPassword username(String username) {
    this.username = username;
    return this;
  }

  

  /**
  * The user&#x27;s login name. May be required.
  * @return username
  **/
  //(description = "The user's login name. May be required.")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }
  public ForgottenPassword newPassword(String newPassword) {
    this.newPassword = newPassword;
    return this;
  }

  

  /**
  * The password to be set.
  * @return newPassword
  **/
  //(required = true, description = "The password to be set.")
  public String getNewPassword() {
    return newPassword;
  }
  public void setNewPassword(String newPassword) {
    this.newPassword = newPassword;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForgottenPassword forgottenPassword = (ForgottenPassword) o;
    return Objects.equals(this.token, forgottenPassword.token) &&
        Objects.equals(this.secretAnswer, forgottenPassword.secretAnswer) &&
        Objects.equals(this.username, forgottenPassword.username) &&
        Objects.equals(this.newPassword, forgottenPassword.newPassword);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(token, secretAnswer, username, newPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForgottenPassword {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    secretAnswer: ").append(toIndentedString(secretAnswer)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
