/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
//.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * PasswordExpired
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class PasswordExpired {

  @SerializedName("message")
  private String message = null;

  @SerializedName("changePasswordURL")
  private String changePasswordURL = null;
  public PasswordExpired message(String message) {
    this.message = message;
    return this;
  }

  

  /**
  * The password expired message.
  * @return message
  **/
  //(description = "The password expired message.")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }
  public PasswordExpired changePasswordURL(String changePasswordURL) {
    this.changePasswordURL = changePasswordURL;
    return this;
  }

  

  /**
  * The change password URL.
  * @return changePasswordURL
  **/
  //(description = "The change password URL.")
  public String getChangePasswordURL() {
    return changePasswordURL;
  }
  public void setChangePasswordURL(String changePasswordURL) {
    this.changePasswordURL = changePasswordURL;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordExpired passwordExpired = (PasswordExpired) o;
    return Objects.equals(this.message, passwordExpired.message) &&
        Objects.equals(this.changePasswordURL, passwordExpired.changePasswordURL);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(message, changePasswordURL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordExpired {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    changePasswordURL: ").append(toIndentedString(changePasswordURL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
