/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;

import org.mule.runtime.extension.api.annotation.param.Optional;
import org.mule.runtime.extension.api.annotation.param.Parameter;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
//.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * SecretQuestion
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class SecretQuestion {

  @Parameter
  @SerializedName("password")
  private String password = null;

  @Parameter
  @SerializedName("secretQuestion")
  private String secretQuestion = null;

  @Parameter
  @SerializedName("secretAnswer")
  private String secretAnswer = null;
  public SecretQuestion password(String password) {
    this.password = password;
    return this;
  }

  

  /**
  * The user&#x27;s password.
  * @return password
  **/
  //(required = true, description = "The user's password.")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }
  public SecretQuestion secretQuestion(String secretQuestion) {
    this.secretQuestion = secretQuestion;
    return this;
  }

  

  /**
  * The secret question text.
  * @return secretQuestion
  **/
  //(required = true, description = "The secret question text.")
  public String getSecretQuestion() {
    return secretQuestion;
  }
  public void setSecretQuestion(String secretQuestion) {
    this.secretQuestion = secretQuestion;
  }
  public SecretQuestion secretAnswer(String secretAnswer) {
    this.secretAnswer = secretAnswer;
    return this;
  }

  

  /**
  * The associated answer.
  * @return secretAnswer
  **/
  //(required = true, description = "The associated answer.")
  public String getSecretAnswer() {
    return secretAnswer;
  }
  public void setSecretAnswer(String secretAnswer) {
    this.secretAnswer = secretAnswer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecretQuestion secretQuestion = (SecretQuestion) o;
    return Objects.equals(this.password, secretQuestion.password) &&
        Objects.equals(this.secretQuestion, secretQuestion.secretQuestion) &&
        Objects.equals(this.secretAnswer, secretQuestion.secretAnswer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(password, secretQuestion, secretAnswer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecretQuestion {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    secretQuestion: ").append(toIndentedString(secretQuestion)).append("\n");
    sb.append("    secretAnswer: ").append(toIndentedString(secretAnswer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
