/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
//.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * ServerTime
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class ServerTime {

  @SerializedName("requestArrivalTime")
  private String requestArrivalTime = null;

  @SerializedName("responseDepartureTime")
  private String responseDepartureTime = null;
  public ServerTime requestArrivalTime(String requestArrivalTime) {
    this.requestArrivalTime = requestArrivalTime;
    return this;
  }

  

  /**
  * The server time when request is received. The date format is &#x60;yyyy-MM-dd&#x27;T&#x27;HH:mm:ss.SSS&#x27;Z&#x27;&#x60; and conforms to ISO-8601 date formatting standard
  * @return requestArrivalTime
  **/
  //(description = "The server time when request is received. The date format is `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` and conforms to ISO-8601 date formatting standard")
  public String getRequestArrivalTime() {
    return requestArrivalTime;
  }
  public void setRequestArrivalTime(String requestArrivalTime) {
    this.requestArrivalTime = requestArrivalTime;
  }
  public ServerTime responseDepartureTime(String responseDepartureTime) {
    this.responseDepartureTime = responseDepartureTime;
    return this;
  }

  

  /**
  * The server time when response is sent. The date format is &#x60;yyyy-MM-dd&#x27;T&#x27;HH:mm:ss.SSS&#x27;Z&#x27;&#x60; and conforms to ISO-8601 date formatting standard.
  * @return responseDepartureTime
  **/
  //(description = "The server time when response is sent. The date format is `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` and conforms to ISO-8601 date formatting standard.")
  public String getResponseDepartureTime() {
    return responseDepartureTime;
  }
  public void setResponseDepartureTime(String responseDepartureTime) {
    this.responseDepartureTime = responseDepartureTime;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerTime serverTime = (ServerTime) o;
    return Objects.equals(this.requestArrivalTime, serverTime.requestArrivalTime) &&
        Objects.equals(this.responseDepartureTime, serverTime.responseDepartureTime);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(requestArrivalTime, responseDepartureTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerTime {\n");
    
    sb.append("    requestArrivalTime: ").append(toIndentedString(requestArrivalTime)).append("\n");
    sb.append("    responseDepartureTime: ").append(toIndentedString(responseDepartureTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
