/*
 * SecureTransport End-User API v1.4
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.4.1
 * Contact: support@axway.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.avodagroup.securetransport.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
//.client.model.SharedFolder;
//.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SharedFolders
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-04T10:29:31.230-04:00[America/New_York]")public class SharedFolders {

  @SerializedName("sharedFolders")
  private List<SharedFolder> sharedFolders = null;
  public SharedFolders sharedFolders(List<SharedFolder> sharedFolders) {
    this.sharedFolders = sharedFolders;
    return this;
  }

  public SharedFolders addSharedFoldersItem(SharedFolder sharedFoldersItem) {
    if (this.sharedFolders == null) {
      this.sharedFolders = new ArrayList<SharedFolder>();
    }
    this.sharedFolders.add(sharedFoldersItem);
    return this;
  }

  /**
  * List of shared folders
  * @return sharedFolders
  **/
  //(description = "List of shared folders")
  public List<SharedFolder> getSharedFolders() {
    return sharedFolders;
  }
  public void setSharedFolders(List<SharedFolder> sharedFolders) {
    this.sharedFolders = sharedFolders;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SharedFolders sharedFolders = (SharedFolders) o;
    return Objects.equals(this.sharedFolders, sharedFolders.sharedFolders);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(sharedFolders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharedFolders {\n");
    
    sb.append("    sharedFolders: ").append(toIndentedString(sharedFolders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
